### ISSUE TITLE
Arbitrary file upload with arbitrary file-extensions in images of badges.

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#35]
It is possible for an attacker to upload arbitrary files with arbitrary extensions that are publicly accessible.
This could be a javascript payload, or other content used in more complex attacks.

`LocalBadgeInstanceUploadSerializer.create()` creates badges with an image like this:
```
new_instance, instance_created = LocalBadgeInstance.objects.get_or_create({
...
    'image': use_or_bake_badge_instance_image(validated_data.get('image'), badge_instance, badge_class)
}, identifier=badge_instance_url, recipient_user=request_user)
```
The image is set by running `use_or_bake_badge_instance_image()` which contains:
```
if uploaded_image and verify_baked_image(uploaded_image):
    baked_badge_instance = uploaded_image  # InMemoryUploadedFile
```
it then stores our payload like this with our own file extension:
```
_, image_extension = os.path.splitext(baked_badge_instance.name)
baked_badge_instance.name = \
    'local_badgeinstance_' + str(uuid.uuid4()) + image_extension
return baked_badge_instance
```
How can we fool this check verify_baked_image() to store our payload?
```
def verify_baked_image(uploaded_image):
    try:
        unbake(uploaded_image)
    except Exception:
        return False

    return True
```
It seems we only need to run `unbake()` without throwing an exception:
```
def unbake(image_file):
    """
    Return the openbadges content contained in a baked image.
    """
    image_type = check_image_type(image_file)
    image_file.seek(0)
    if image_type == 'PNG':
        return png_bakery.unbake(image_file)
    elif image_type == 'SVG':
        return svg_bakery.unbake(image_file)
```
To avoid running too much checks we only need to make sure that the
filetype is neither identified as PNG nor SVG, this check is done like
this:
```
def check_image_type(image_file):
    if image_file.read(8) == '\x89PNG\r\n\x1a\n':
        return 'PNG'
    image_file.seek(0)
    # TODO: Use xml library to more accurately detect SVG documents
    if re.search('<svg', image_file.read(256)):
        return 'SVG'
```
So our payload cannot start with a PNG header and cannot contain
`<svg` in the first 256 bytes, that is quite possible for our payload.

We can trigger `LocalBadgeInstanceUploadSerializer.create()` by
sending a POST request to `LocalBadgeInstanceList` at
`/v1/earner/badges` and providing a correct payload in the image
parameter that has a `.js` extension and javascript content.

Recommendations: 
  - force the correct file extension,
  - serve from unrelated domain,
  - validate the contents of the images,
  - filter out javascript.

**Comment by ottonomy** [comment]
I don't think we have forced any file extensions, but the library that handles baking and importing has changed massively from the version under test. The openbadges library is used for verification and the openbadges_bakery library is used for baking. These libraries are also released by the authors of badgr-server and still contain a few of the snippets related to this issue. 

It's possible that there was a possible exploit along these lines with the old version under test, but the LocalBadgeInstance would only ever be saved if the file uploaded was actually a valid open badge (meaning that it validated the contents of the image, which would only be possible if it was a valid PNG or valid SVG/XML), so it's unlikely that a .js file could be successfully saved.  In more recent updates, included in all versions ever run on the proof of concept server by SURFnet, we've added a filter for scripts of various sorts within otherwise valid SVGs.

Not sure what you mean by "serve from unrelated domain", but it is possible and recommended to set the MEDIA_URL to an external server from badgr-server for production.
